spring:
  datasource:
    driver-class-mame: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password:

jpa:
  hibernate:
    ddl-auto: none
  show-sql: false
